shorten/web/models.py
from flask_wtf import Form
from wtforms import URLField
from wtforms import validators
from flask_sqlalchemy import SQLAlchemy
import datetime

db = SQLAlchemy()

class Shorten_urls(db.Model):
    shorten_url = db.Column(db.String(10), primary_key=True) # primary keys are required by SQLAlchemy
    full_url = db.Column(db.String(100), unique=True)
    email = db.Column(db.String(100),default = "abc@gmail.com")
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    def __str__(self):
        return f"Short: {self.shorten_url} \n Full {self.full_url} \n Email {self.email} \n Created {self.created_at}"
class NewShortendURL(Form):
    url = URLField('url',[validators.DataRequired()])

    

shorten/__init__.py
from flask import Flask
from flask_wtf import CSRFProtect
app = Flask(__name__,instance_relative_config=True)
app.config.from_pyfile("app_configs.py")

from shorten.web.views import web
app.register_blueprint(web)
csrf = CSRFProtect(app)
from shorten.web.models import db
db.init_app(app)
with app.app_context():
    db.create_all()

shorten/web/views.py
from flask import Blueprint,render_template,request,flash,redirect,jsonify
from shorten.web.models import NewShortendURL
import shorten.utils.sql_utils as sql_utl

web = Blueprint('web', __name__)

@web.errorhandler(404) 
def invalid_route(e): 
    return jsonify({'errorCode' : 404, 'message' : 'Route not found'})

@web.route('/',methods=['GET','POST'])
def home():
    form = NewShortendURL(request.form)
    if request.method=='POST' and form.validate:
        user_url = request.form['url']
        is_shortened = sql_utl.get_shortened_url(user_url)
        if(is_shortened is None):
            new_short_url = sql_utl.add_new_mapping(user_url)
            flash(f"URL Shortened successfully {request.base_url +new_short_url}","success")
        else:
            flash(f"URL already shortened earlier {request.base_url +is_shortened}","warning")

        return render_template('home.html',form=form,all_mappings = sql_utl.get_all_url_mappings(),base_url = request.base_url)
    else:
        return render_template('home.html',form=form,all_mappings = sql_utl.get_all_url_mappings(),base_url = request.base_url )

@web.route('/<short_url>')
def go_to_url(short_url):
    mapping = sql_utl.get_long_url(short_url)
    if mapping is None:
        return render_template("error.html"),404
    else:
        return redirect(mapping)

shorten/templates/error.html
{% extends 'main.html' %}
{% block page_title %} Error {% endblock %}
{% block content_container %}
<div class="my-auto mx-auto">
    <h2 class="text-warning"> URL Not Found</h2>

    <h5> There exist no URL corresponding to the shortened URL you provided. Please check the URL and try again.</h5>

</div>


{% endblock %}

shorten/templates/home.html
{% extends 'main.html' %}
{% block page_title %} Shortener - Home {% endblock %}
{% block content_container %}
<div class="d-flex mb-3 justify-content-between align-items-center">
  <div class="p-1">
    <h4>
      Shorten a new URL:
    </h4>
    
  </div>
  
</div>
<form method="POST" action="{{ url_for('web.home') }}" role="form">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  <div class=" mb-3">
    {{ form.url(class="form-control form-control-lg",placeholder = "Enter the URL to be shortened") }}
  </div>
  <div class="row mb-3 justify-content-center">
    <button type="submit" class="btn btn-lg btn-success col-xs-12 col-md-3">Submit</button>
  </div>        
</form>

{% if all_mappings|length >1 %}
<div class="card mt-5">
  <div class="card-header">
   Latest Shortened URLs (max 10)
  </div>
  <div class="card-body">
    {% for mapping in all_mappings %}
    <div class="row">
      <div class="col-xs-12 col-md-5">
        <a class="text-decoration-none" target="_blank" href="{{mapping['full_url']}}">{{mapping['full_url']}} </a>
      </div>
      <div class="col-xs-12 col-md-4">
        <a class="text-decoration-none"  target="_blank" href="{{base_url}}{{mapping['shorten_url']}}">{{base_url}}{{mapping['shorten_url']}}</a>
      </div>
      <div class="col-xs-12 col-md-3">
        {{mapping['created_at'].strftime('%Y-%m-%d') }}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}

  
{% endblock %}

shorten/templates/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favico.gif') }}">
    <title>{% block page_title %} {% endblock %}</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
  </head>

  <body class="bg-light"> 
    <div id="navbar_main_section">
      <nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark px-2" role="navigation">
        <a href="{{ url_for('web.home') }}" class="navbar-brand active text-decoration-none">
          URL Shortener
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">            
            {% block nav_dropdown %}
            {% endblock %}        
        </div>
    
      </nav>    
    </div>
    
    <div class="container">
      <br/>
      <div class="d-flex justify-content-center align-items-center">
        {% for category, message in get_flashed_messages(with_categories=true) %}
          <div class="alert alert-{{category}} alert-dismissable">
            <button type="button"class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
            {{ message }}
          </div>
        {% endfor %}
        {% if form and form.errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
          {% for error_field in form.errors %}
              {% for rec_error in form.errors[error_field] %}
              {{ rec_error }}
              {% endfor %}
          {% endfor %}
        </div>
        {% endif %}
      </div>


      {% block content_container %}
      {% endblock %}


    </div>
  
    
    {% block scripts %}
    {% endblock %}
  </body>
</html>